### ISSUE TITLE
Did not find any deprecated APIs

### ISSUE THREAD

**Issue by mawwerik** [hickeyma/helm-mapkubeapis#11]
I'm using HELM 2.16.7. HELM was not able to make the update: Error: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

I used your tool, but it did not find any problem in the last deployment.
2020/05/06 14:35:39 Finished checking release 'icms-uat' for deprecated or removed APIs.
2020/05/06 14:35:39 Release 'icms-uat' has no deprecated or removed APIs.

Could you pls check what can be the problem?

**Comment by hickeyma** [comment]
@mawwerik What version of the plugin are you using?

**Comment by mawwerik** [comment]
Can it happen that CRLF is stored in the configmap instead of a LF? 
So, ```apps/v1beta1\nkind``` will not be found.

Could you pls extend the string mapping with CRLF versions?
like ```apps/v1beta1\r\nkind```

**Comment by mawwerik** [comment]
I'm using v0.0.9

**Comment by hickeyma** [comment]
@mawwerik Thanks for update in https://github.com/hickeyma/helm-mapkubeapis/issues/11#issuecomment-624646968. I am due to do some work around this area and how handle search/replace. t was on my queue! :)

**Comment by hickeyma** [comment]
I will try and get to this once have some bandwidth.

**Comment by mawwerik** [comment]
Thank you in advance... I appreciate your efforts for making this plugin. It would save me and others a lot.

**Comment by mawwerik** [comment]
In may case the solution was to add ```kind``` and ```apiVersion``` in the opposite order in ```common.go```.
for example: "kind: Deployment\napiVersion: extensions/v1beta1"

**Comment by hickeyma** [comment]
@mawwerik Do you mind showing the deployment template from the chart which deployed the release?

**Comment by mawwerik** [comment]
I can show you the beginning of the deployment template that I use
```kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "application.fullname" . }}
  namespace: {{ required "Namespace is required" .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}```

**Comment by mawwerik** [comment]
@hickeyma with the change that I suggested I managed to fix all my HELM upgrade issues, so I would like to thank you again for creating this plugin. I'm very thankful !!!

**Comment by hickeyma** [comment]
@mawwerik Not a bother. I will do an update as soon as possible.
It is funny to see that the manifests are written in different formats. Might make it difficult to do a robust mapping as a consequence but will look to improve it.

**Comment by hickeyma** [comment]
@mawwerik Have a look at [API Mapping](https://github.com/hickeyma/helm-mapkubeapis#api-mapping) on how to configure the mapping for different search and replace strings. This should enable to configure the mappings on the fly now instead of changing in code.

**Comment by mawwerik** [comment]
@hickeyma Excellent solution... Thanks.
