### ISSUE TITLE
Release has no deprecated or removed APIs

### ISSUE THREAD

**Issue by branttaylor** [hickeyma/helm-mapkubeapis#12]
This helm release fails to upgrade with this message:

```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

But running a `helm mapkubeapis XXX -n kube-system` does not find any APIs that are at issue:
```
2020/05/07 11:30:48 Release 'XXX' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/05/07 11:30:48 Get release 'XXX' latest version.
2020/05/07 11:30:49 Check release 'XXX' for deprecated or removed APIs...
2020/05/07 11:30:49 Finished checking release 'XXX' for deprecated or rempved APIs.
2020/05/07 11:30:49 Release 'XXX' has no deprecated or removed APIs.
2020/05/07 11:30:49 Map of release 'XXX' deprecated or removed APIs to supported versions, completed successfully.
```

Versions:
- Kubernetes 1.16.9
- Helm 3.2.0
- Helmfile 0.114.0
- mapkubeapis 0.0.9

Side note, I also noticed a typo in the output: `rempved`

**Comment by hickeyma** [comment]
@branttaylor Thanks for raising this issue. I think it probably is related to #11 and work I need to do around the search and replace which is on my queue. I hope to get to this shortly. 

One thing. What OS are you running Helm on?

**Comment by branttaylor** [comment]
We apply our Helm configs to our clusters in a CircleCI pipeline using Helmfile, and the image has an Alpine base. I'm using macOS Mojave to run local Helm commands, including this plugin.

**Comment by hickeyma** [comment]
Fixed in PR #14 and available in [v0.0.12](https://github.com/hickeyma/helm-mapkubeapis/releases/tag/v0.0.12).

**Comment by hickeyma** [comment]
@branttaylor Have a look at [API Mapping](https://github.com/hickeyma/helm-mapkubeapis#api-mapping) on how to configure the mapping re line feeds for release manifests rendered with Mac.

**Comment by branttaylor** [comment]
Looks great! Thanks @hickeyma!
