### ISSUE TITLE
kube version has a plus in the minor version string

### ISSUE THREAD

**Issue by phroggyy** [hickeyma/helm-mapkubeapis#25]
The response from `kubeVersion.Minor` [here](https://github.com/hickeyma/helm-mapkubeapis/blob/master/pkg/common/common.go#L117) will be e.g `16+` rather than `16`. This means that `strconv.ParseFloat` fails, as `1.16+` cannot be properly parsed.

I'm creating an issue because I'm not certain of the best way to tackle this – do we just want to drop the `+`? Should we rely on `GitVersion` instead?

The advantage of `GitVersion` would be that we can do a proper semver compare, as versions like `v1.16.6-beta.0` or `v1.16.8-gke.15` are both valid SemVer versions, and can be properly compared against e.g `"1.9"`. This would also make the `Map.yaml` a bit more readable as we could do `"1.9"` rather than `"1.09"` which looks a bit weird (after all, it _is_ version 1.9).

Happy to PR this once there's some decision on how we want to do the version comparison :)

**Comment by hickeyma** [comment]
@phroggyy Thanks for raising this.

I didn't see the `+` in `kubeVersion.Minor` while adding the feature. I was however unhappy having to set `"1.09"` alright and was hoping to return to it when I got a chance. I wanted to deliver the feature first as it would be helpful to users.

I would be delighted if you want to push a PR for this. I am interested how you can compare with SemVer versions which would also hopefully remove need for conversations. Assigning it to you.

**Comment by phroggyy** [comment]
Sure, I'll have a look at this. From a quick glance it seems `GitVersion` should be reliable for a SemVer tag https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L70-L72 so I'll work off that.

**Comment by flowjo-shaunr** [comment]
I don't want to step on your toes @phroggyy, but I have a fix using `GitVersion` that compares the versions using the [semver](https://godoc.org/golang.org/x/mod/semver) package and checks the version string's validity.

**Comment by phroggyy** [comment]
@flowjo-shaunr no toe stepping at all! That was exactly what I was going to do, beyond happy that someone else has already done the work 😄

**Comment by hickeyma** [comment]
Looking forward to whoever pushes the PR! 😄  Great stuff @phroggyy @flowjo-shaunr 👍

**Comment by eloo** [comment]
i've just came across this bug and tested the pr from @flowjo-shaunr 
looks good so far.

but it still looks like some errors are just ignored like here (current master)
```
	kubeVersion, err := strconv.ParseFloat(kubeVersionStr, 32)
	if err != nil {
		errors.Wrap(err, "Failed to get Kubernetes server version")
	}
```
errors.Wrap returns an error which is ignored.. AFAIK this will not logged or fail the process

**Comment by hickeyma** [comment]
@eloo I reviewed the PR #28 and added comments there. Probably best add them in there, instead of the issue.

**Comment by hickeyma** [comment]
Thanks @flowjo-shaunr for pushing a PR for this. The addition of semver checking improves robustness and usability to the plugin. 👏
