### ISSUE TITLE
Ability to update chart templates

### ISSUE THREAD

**Issue by eloo** [hickeyma/helm-mapkubeapis#29]
Hi, 
maybe its possible to also update self created charts with this plugin? 
For example to just pass a --chart parameter and a path and then the template files will be adjusted?

What do you think?

Best regards
eloo

**Comment by hickeyma** [comment]
Hey @eloo, thanks for raising. Nice idea but I don't think that this should be in scope for the plugin. The plugins main goal is updating releases in cluster. There are also a lot of tools out there for updating YAML files in a directory.

**Comment by eloo** [comment]
hmm okay
was just thinking about it while i was using the mapping.yaml which holds exactly the necessary information.

Thanks

**Comment by hickeyma** [comment]
Good that you raised this. I think the updating of charts should be performed by maintainers and owners outside of the plugin. They can use the mapping file as a reference. The plugin is to automate the steps to update release metadata in cluster, which are quite difficult to do.

Going to close this as answered.
