### ISSUE TITLE
mapkubeapis only updates last release even if it is in FAILED state

### ISSUE THREAD

**Issue by sky-philipalmeida** [hickeyma/helm-mapkubeapis#33]
We recently had an issue with mapkubeapis only updating last release even if it is in FAILED state.
The cluster was updated, there was a pipeline deployment that failed with the correct apis but as mapkubeapis updated only the last failed we could not get the build to success.
To fix it we delete all failed releases (but not the deployed one) replayed mapkubeapis that then updated the deployed one and after that we were able to push the pipeline since the previous version was updated.

Sugestion by default war if last release is failed and ask to remove all failed ?

**Comment by hickeyma** [comment]
@sky-philipalmeida Thanks for raising this issue. The plugin is working as expected as it calls the Helm API to return the latest release. It is expected that when you want to run the plugin on a release then that is a successfully deployed release.

> Sugestion by default war if last release is failed and ask to remove all failed ?

This is a good suggestion but not in scope for the plugin. I would prefer keeping the plugin to the one job of updating release APIs and not having to also resolve release status issues.

**Comment by hickeyma** [comment]
I think that it would be worth updating the doc further in [Prerequisite](https://github.com/hickeyma/helm-mapkubeapis#prerequisite) section to expand of `failed` releases. I will assign this then as a doc issue.
