### ISSUE TITLE
Issue with NetworkPolicy

### ISSUE THREAD

**Issue by N4rm0** [hickeyma/helm-mapkubeapis#36]
Hello,

After launching the plugin v0.0.14 to remove deprecated api, I encountered the following error when performing hem upgrade.

```
$ helm upgrade --install releaseName --dry-run
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: error parsing : error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
``` 

After some investigation I found out the network policy object is incorrectly mapped during the api replacement.

```
$ helm get manifest releaseName
[...]
# Source: chart/templates/networkpolicy.yaml
**apiVersion: apiVersion: networking.k8s.io/v1**  
kind: NetworkPolicy
[...]
``` 

The field apiVersion is incorrectly set in helm and breaks the release.

**Comment by hickeyma** [comment]
Merge of #37 fixes this issue.
