### ISSUE TITLE
this is a great helm plugin. thanks ~

### ISSUE THREAD

**Issue by oldthreefeng** [hickeyma/helm-mapkubeapis#43]
we have a lot of deployment made by helm in k8s v1.14. we upgrade k8s to 1.18.
 
then The annoying thing is coming。offical helm v2 does not have the right way to slove this . 
even I change the chart apiserver to apps/v1. 
```
Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
```

you guys doing the great things .

**Comment by hickeyma** [comment]
@oldthreefeng So does the plugin help you get over this issue?

**Comment by oldthreefeng** [comment]
@hickeyma  yes.

**Comment by hickeyma** [comment]
Great, thanks for taking the time out for your kind words.

**Comment by oldthreefeng** [comment]
I think if people Use helm and upgrade there k8s version . they will meet the same problem. 
on a PROD cluster. Reinstalling the helm release was not an option.
Your tool perfectly solves this problem。

**Comment by tretos53** [comment]
I just want to say Thank you to everyone who developed this plugin.

**Comment by hickeyma** [comment]
Thanks for the kind words @oldthreefeng @tretos53.

Closing as answered.
