### ISSUE TITLE
Deployment from Helm 2 to Helm3 is not correct mapped

### ISSUE THREAD

**Issue by MarkusKepert** [hickeyma/helm-mapkubeapis#45]
I have a kube Cluster 1.17 with old helm2 deployments.
During migration to helm, i've added mapkupeapis to helm3 instance. But some mappings was not done successful, currently because of unknow reason:

Output from helm command:
![image](https://user-images.githubusercontent.com/6367277/116421752-6b356700-a83f-11eb-8142-2363a8144fcd.png)

Output from release.yaml after running mapkubeapi command:
![image](https://user-images.githubusercontent.com/6367277/116421850-81432780-a83f-11eb-941f-852649a883cd.png)

Any hint how to debug this?

**Comment by hickeyma** [comment]
@MarkusKepert Can you provide more details on what mappings were not done successfully? Did it now find the mappings? What are the mappings you refer to?

Just trying to get more details to help troubleshoot this.

**Comment by MarkusKepert** [comment]
Hi @hickeyma for this problematic deployment i had to help myself with the "hard way", editing the release data directly. I have no idea...other self written deployments with same helm chart was converted properly. Maybe you can give me a hint, how to collect more information. I have an other cluster where i should perform same action (from same customer with hopefully same deployments)

**Comment by hickeyma** [comment]
It would depend on which API versions where not found. It could be the search string did not match against how it was stored. Then it is a matter of changing the mapping file to match.

Re to troubleshooting this further, It is very hard to identify without you showing what API versions should have showed up as an issue. Would need to identify this.

**Comment by hickeyma** [comment]
Ok @MarkusKepert, we can re-open when you have more details.
