### ISSUE TITLE
Add support for rbac.authorization.k8s.io API changes

### ISSUE THREAD

**Issue by chadlwilson** [hickeyma/helm-mapkubeapis#8]
When trying to migrate `kube2iam` chart from `2.0.1` to `2.1.0`+, got similar errors as noted in https://github.com/helm/helm/issues/7219

This tool was able to help us patch the release for the `DaemonSet` `apiVersion` change to `apps/v1` (thanks!) but unable to fix the APIs for the `ClusterRole` and `ClusterRoleBinding`.

I'm not sure of the wider consequences thereof, but seems this tool could also potentially help map
`rbac.authorization.k8s.io/v1beta1`
to
`rbac.authorization.k8s.io/v1`

This would presumably also affect `Role` and `RoleBinding`.

Example chart change to assist with testing.
https://github.com/helm/charts/commit/0361720773930fdea94811e53bf12b8b6ae1b7cb#diff-93cdf1f4ea0c4b64a41c7ff4a84a60c2

**Comment by hickeyma** [comment]
Thanks for raising @chadlwilson. I will push a PR shortly to add them.

**Comment by chadlwilson** [comment]
Thank you sir!

**Comment by orankaplan** [comment]
Hey, I'm still having issues when trying to upgrade nginx-ingress to version 1.27.1 - https://github.com/helm/charts/commit/5978272b31765d38ad01405bd34cbb7a7cc3a845,
I'm getting 
`helm.go:84: [debug] ClusterRole "ingress-controller-websocket-nginx-ingress" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "ingress-controller-websocket"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "hb-generic"
rendered manifests contain a resource that already exists. Unable to continue with update
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/pkg/action/upgrade.go:287
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/pkg/action/upgrade.go:130
main.newUpgradeCmd.func1
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/upgrade.go:144
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/asm_amd64.s:1357
UPGRADE FAILED
main.newUpgradeCmd.func1
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/upgrade.go:146
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/asm_amd64.s:1357`
helm version 3.2.1 and plugin version 0.0.12
any idea why?
